### ISSUE TITLE
Implement Remaning Actor Values

### ISSUE THREAD

**Issue by mlthelama** [mlthelama/SkyrimCharacterSheet#26]
See Title.

**Comment by bziqqq** [comment]
Still Wait)

**Comment by mlthelama** [comment]
I am currently implementing it in the [dev](https://github.com/mlthelama/SkyrimCharacterSheet/blob/dev/config/SkyrimCharacterSheet_Player.json) branch to have more options to configure. The used id should be taken from [here ](https://github.com/CharmedBaryon/CommonLibSSE-NG/blob/main/include/RE/A/ActorValues.h). the "key" can be whatever, it is mostly used to handle some values without an actor value i use or for special handlings. there is an enum behind the key, for non defined values in my mod the key internal will be just "custom".

I will release some kind of documenation if the code is done and cleaned up.

**Comment by mlthelama** [comment]
[beta build](https://github.com/mlthelama/SkyrimCharacterSheet/releases/tag/1.1.0-beta) configuration for the additional values have to be done in  file that starts with SkyrimCharacterSheet_Player and ends with .json

**Comment by mlthelama** [comment]
#28
