### ISSUE TITLE
Support for Blande and Blunt 3.0

### ISSUE THREAD

**Issue by ribeirojc1** [mlthelama/SkyrimCharacterSheet#27]
It has a different damage reduction formula from vanilla.
Each point of Armor Rating reduces incoming damage by 0.15%, up to 75% damage reduction at 500 Armor Rating. This represents the “soft cap” for Armor Rating. Increasing your Armor Rating beyond 500 reduces incoming damage by 0.03% per point, up to a total reduction of 90% damage reduction at 1000 Armor Rating. This represents the “hard cap” for Armor Rating. 

See attached image.
Thanks!

![image](https://github.com/mlthelama/SkyrimCharacterSheet/assets/91457791/da85c817-97af-4b7a-8e5f-bdf9a4d4fa34)

**Comment by mlthelama** [comment]
#28
