### ISSUE TITLE
Damage resistance with 1.1.0 and Blade and Blunt is bugged

### ISSUE THREAD

**Issue by stephan13360** [mlthelama/SkyrimCharacterSheet#38]
First of all, great mod, exactly what i was looking for.

I just tried the new 1.1.0 version from GitHub since I saw that the armor calculation from blade and blunt is now supported, but the display is incorrect.

I currently have 120 armor, the damage resistance shows 0.90 % where it should be 18 %.
When only wearing the worst armor item I have with 7 Armor it shows 0.75 % where it should be 1,05 %
When wearing no armor, it shows 0%.
When I deactivate Blade and Blunt it shows 26,4 %, which is correct for vanilla values.

Since 0.9 and 0.75 are both the hard and soft cap of blade and blunt, it feels like the armor caps are returned and not the actually values.

If I can you assist further or give you more information, let me now.

**Comment by mlthelama** [comment]
oh ok thanks for the info, will take a look at it

**Comment by colinswrath** [comment]
> oh ok thanks for the info, will take a look at it
Author of b&b here. 
Not sure if this is related to this person's specific issue, but I can see a section of the calculation uses the "armorBaseFactor" game setting. This should be incorrect as b&b sets this game setting to 0. 

The calculation should roughly match this section of code here in b&b.

**Comment by mlthelama** [comment]
I will take a look at it and update my code if needed.

**Comment by mlthelama** [comment]
added a fix for the issue. will push it on nexus with a release if i have a other feature done. and then close the ticket

(i could trigger beta build since github will do everything for me xD).

**Comment by mlthelama** [comment]
fixed and pushed to nexus and github. version 1.1.1
